Aqa/js conditions loops
Denys-Naumenko/AQA-JavaScript-Advanced pull request #5
Opened 2023-09-27 19:59 UTC by Denys-Naumenko

This merge request serves as a practical exercise for reinforcing understanding of conditions and loops in JavaScript.

2023-09-28 19:58 UTC, landriiuk requested changes

2023-09-28 19:58 UTC, landriiuk commented on js-conditions-loops/conditionsAndloops.js
> +console.log(chalk.greenBright(biggerNumber));
you have to write it using the ternary operator. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator

2023-09-28 19:58 UTC, landriiuk commented on js-conditions-loops/conditionsAndloops.js
> +  formatedMessage += currentChar;
```suggestion
  formattedMessage += currentChar;
```

2023-09-28 19:58 UTC, landriiuk commented on js-conditions-loops/conditionsAndloops.js
> +let formatedMessage ="";
```suggestion
let formattedMessage ="";
```

2023-09-28 19:58 UTC, landriiuk commented on js-conditions-loops/conditionsAndloops.js
> +}
This code works, but it's hard to read. you can simplify. 
```suggestion
let employeeExperience = 0.5;// or full month format 12 month = 1 year
let employeeSalary;
let employeeBonus;


if (employeeExperience < 0.5) { // if you're gonna use full month format then here should be 6 
    employeeSalary = 0;
    employeeBonus = 0;
} else if (employeeExperience >= 0.5 && employeeExperience < 1) {// if you're gonna use full month format then here should be 6 and 12
    employeeSalary = 100;
    employeeBonus = employeeSalary * 0.01;
}
..... 
```

2023-09-28 19:58 UTC, landriiuk commented
there to points that need to be reworked.

2023-10-02 13:36 UTC, Denys-Naumenko commented on js-conditions-loops/conditionsAndloops.js
> +}
fix this, please check new commit

2023-10-02 13:36 UTC, Denys-Naumenko commented on js-conditions-loops/conditionsAndloops.js
> +console.log(chalk.greenBright(biggerNumber));
fix this, please check new commit

2023-10-02 13:36 UTC, Denys-Naumenko commented on js-conditions-loops/conditionsAndloops.js
> +let formatedMessage ="";
fix this, please check new commit

2023-10-02 13:36 UTC, Denys-Naumenko commented on js-conditions-loops/conditionsAndloops.js
> +  formatedMessage += currentChar;
fix this, please check new commit

2023-10-02 20:45 UTC, landriiuk approved these changes

2023-10-02 20:46 UTC, landriiuk commented
Well done. Thanks. You can merge this pr into main

2023-10-04 17:36 UTC, merged